name: ci
on: [push, pull_request, workflow_dispatch]

jobs:
  build-bookworm:
    name: Linux (Debian bookworm amd64)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - run: make ci-bookworm
  build-bookworm-arm64:
    name: Linux (Debian bookworm arm64)
    runs-on: ubuntu-24.04-arm
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - run: make ci-bookworm
      env:
        PLATFORM: linux/arm64
  build-oldest:
    name: Linux (oldest Rust)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - run: make ci-oldest
  build-stable:
    name: Linux (Rust stable)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - run: make ci-stable
  build-mac:
    name: macOS
    runs-on: macos-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v3
    - run: brew unlink pkg-config@0.29.2 || true
    - run: brew install ruby asciidoctor rust
    - run: gem install rspec
    - run: mkdir ~/tmp
    - run: TMPDIR="$HOME/tmp" make test-full
